{
 "title": "Stardog Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dbms Memory Heap Query Blocks Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dbms_memory_heap_used", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Cluster Fullsync Attempts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cluster_fullsync_attempts", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "User Threads Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "user_threads_size", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Databases Open connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "databases_openConnections",
     "legendFormat": "{{database_name}} - Pod: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Databases Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "databases_size",
     "legendFormat": "{{database_name}} - Pod: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Databases Plancache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "databases_planCache_size",
     "legendFormat": "{{database_name}} - Pod: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dbms Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dbms Memory Heap Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "dbms_memory_heap_used", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Dbms Memory Heap Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "dbms_memory_heap_max", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Dbms Memory Heap Query Blocks Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dbms_memory_heap_query_blocks_used",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Dbms Memory Heap Query Blocks Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dbms_memory_heap_query_blocks_max",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Sync Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Sync Success Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_sync_success_count", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Fullsync Attempts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_fullsync_attempts", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Fullsync Success Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_fullsync_success_count", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Sync Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_sync_running", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Sync Attempt Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_sync_attempt_count", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Sync Failure Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_sync_failure_count", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Cluster Fullsync Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_fullsync_failures", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    }
   ]
  },
  {
   "title": "Users Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Threads Queued",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "user_threads_queued", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "User Threads Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "user_threads_size", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "User Threads Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "user_threads_active", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    }
   ]
  },
  {
   "title": "Admin Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admin Threads Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "admin_threads_active", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Admin Threads Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "admin_threads_size", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    },
    {
     "title": "Admin Threads Queued",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "admin_threads_queued", "legendFormat": "Pod: {{kubernetes_pod_name}}" }
     ]
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime Min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime_min",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime Max",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime_max",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime Mean",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime_mean",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime_count",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime Stddev",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime_stddev",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Currentrequests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_currentRequests",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Com Stardog Http Server 5820 Avgrequesttime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "com_stardog_http_server_5820_avgRequestTime",
       "legendFormat": "Pod: {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Db Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_db_count",
       "legendFormat": "Namespace: {{kubernetes_namespace}} - Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "System Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage",
       "legendFormat": "Namespace: {{kubernetes_namespace}} - Pod: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "milliseconds" }
     ],
     "targets": [
      {
       "expr": "system_uptime",
       "legendFormat": "Namespace: {{kubernetes_namespace}} - Pod: {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}