# Unique Keys

SELECT * FROM <virtual://uniques> {
    ?s rdfs:label ?label ;
       :yearFormed ?yearFormed .
}

# Foreign Keys and Inclusion Dependencies

SELECT * FROM <virtual://fk_example> {
    ?album a :Album ;
       rdfs:label ?title ;
       :band ?band .
    # Including :Band adds a join unless an Albums.band_id->Bands.id fk exists
    ?band a :Band .
    # Including rdfs:label adds the join despite foreign.key.sets
    # ?band rdfs:label ?name .
}

# Denormalized Data - version 1

SELECT * FROM <virtual://denormalized1> {
    ?s a :Actor ;
       rdfs:label ?name .
}

# Denormalized Data - version 2

SELECT * FROM <virtual://denormalized2> {
    [] a :Role ;
        :actor ?actor ;
        :creditedAs ?name .
}

# Denormalized Data - query over an Actors view

SELECT * FROM <virtual://denormalized2> {
    ?s a :Actor ;
       rdfs:label ?name .
}

# Renormalizing by Aggregated Name

SELECT * FROM <virtual://denormalized3> {
    ?s a :Actor ;
       rdfs:label ?name .
}

# Map rdf:type Conservatively

SELECT * FROM <virtual://actors1> {
    ?s a :Actor
}

SELECT * FROM <virtual://actors2> {
    ?s a :Actor
}

# Unique Predicates

SELECT * {
    GRAPH <virtual://predicates> {
        ?s rdfs:label "Tom Hanks"
    }
}

SELECT * {
    GRAPH <virtual://predicates> {
        ?s :name "Tom Hanks"
    }
}

# Mutually Exclusive Templates

SELECT * {
    GRAPH <virtual://predicates> {
        ?s a :Actor .
        ?s rdfs:label "Tom Hanks" .
    }
}

# SQL Functions and Query Outputs

SELECT * FROM <virtual://remakes> {
    :movie:5
        :title ?title ;
        :releaseYear ?year ;
        rdfs:label ?label .
}

SELECT * FROM <virtual://remakes> {
    ?movie a :Movie ;
        :title "A Star is Born" ;
        :releaseYear 2018 ;
        rdfs:label ?label .
}

SELECT * FROM <virtual://remakes> {
    ?movie a :Movie ;
        :title ?title ;
        :releaseYear ?year ;
        rdfs:label "A Star Is Born (2018)" .
}

# FROM vs FROM NAMED

INSERT DATA {
    GRAPH :g1 {
        :a :knows :b, :d .
        :b :knows :c .
    }
    GRAPH :g2 {
        :d :knows :c .
    }
}

SELECT * FROM :g1 FROM :g2 {
    :a :knows ?mutual .
    ?mutual :knows :c .
}

SELECT * FROM NAMED :g1 FROM NAMED :g2 {
    GRAPH ?g {
        :a :knows ?mutual .
        ?mutual :knows :c .
    }
}

# Datasets and Virtual Graphs

SELECT * {
    GRAPH <virtual://datasets1_v1> {
        ?s a :Actor .
        ?s rdfs:label "Tom Hanks" .
    }
}

SELECT * {
    GRAPH <virtual://datasets2_v1> {
        ?s a :Actor .
        ?s rdfs:label "Tom Hanks" .
    }
}

SELECT * FROM NAMED <virtual://datasets1_v1> FROM NAMED <virtual://datasets2_v1> {
    GRAPH ?g {
        ?s a :Actor .
        ?s rdfs:label "Tom Hanks" .
    }
}

SELECT * FROM <virtual://datasets1_v1> FROM <virtual://datasets2_v1> {
    ?s a :Actor .
    ?s rdfs:label "Tom Hanks" .
}

# Unique Predicates, Revisited

SELECT * FROM <virtual://datasets1_v1> FROM <virtual://datasets2_v1> {
    :node:2 a ?type .
}

SELECT * FROM <virtual://datasets1_v2> FROM <virtual://datasets2_v2> {
    ?s a :Actor .
    ?s rdfs:label "Tom Hanks" .
}


