base=http://example.com/base/

jdbc.url=jdbc:mysql://mysql57vg.czcr14gkjyj5.us-east-1.rds.amazonaws.com:3306/examples?allowMultiQueries=true&useSSL=false&serverTimezone=Etc/GMT-8
jdbc.username=mysql57
jdbc.password=qt2DF7dq
jdbc.driver=com.mysql.cj.jdbc.Driver
parser.sql.quoting=ANSI
unique.key.sets=(Albums.id)
foreign.key.sets=(Albums.band_id->Bands.id)
