jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=examples;encrypt=false
jdbc.username=sa
jdbc.password=Examples#2026
jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
parser.sql.quoting=ANSI
testOnBorrow=true
validationQuery=SELECT 1
validationInterval=30000
#unique.key.sets=(Bands.id)
#foreign.key.sets=(Albums.band_id->Bands.id)
#functional.dependency.sets=(Roles.movie_id->Roles.title,Roles.year)
